# Generated by Django 3.2.9 on 2021-12-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211115_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_grind',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
